### ISSUE TITLE
[FEATURE REQUEST] Default Scanning Settings (Mode, Enhance, Whitepaper, Color, Brightness, Contrast)

### ISSUE THREAD

**Issue by CheariX** [Akylas/OSS-DocumentScanner#289]
**Is your feature request related to a problem? Please describe.**

Each time I start a scan, must change the settings to my favorites:

- Tick Image "Enhance" and "Color" (or Whitepaper if desired).
- Decrease "Brightness", increase "Contrast".
- Change the mode to BW (okay, I prefer the normal mode, but I added this for a clear problem description)

**Describe the solution you'd like**

It would be nice if the app would simply "remember" my previos settings across multiple scanns.
Alternativeley, the default settings could be configured in the app settings.

**Describe alternatives you've considered**
Configure the settings after starting each scan.

**Comment by farfromrefug** [comment]
@CheariX thanks for the request. You can edit default scanning settings either from the Camera/settings or from Settings/operations.
Those settings are used for Camera scan documents, but also for imported from PDF/images

**Comment by CheariX** [comment]
Awesome. Thank you for this super quick integration!

Unfortunately, I get some error when I try to open these settings (either via settings/operations or via camera/settings):

![Screenshot_20240923-234336](https://github.com/user-attachments/assets/3fc1be91-35f5-4887-9ede-fe429766fae0)

---

Would it also make sense to include a setting for “automatically enable OCR"?

**Comment by farfromrefug** [comment]
@CheariX really sorry about that. Will fix today!

**Comment by CheariX** [comment]
> @CheariX really sorry about that. Will fix today!

No worries. Thank you for fixing it.

> About OCR will think about it. What bugs me is that then image processing would get really long

True, that was also what raised my concerns. Maybe if it is a setting with an appropriate message/warning, it could be okay.
It also depends on the device's power. It could be okay for some users but not for others.

Maybe it would be better if the processing took place in the background and just showed a little indicator in some corner instead of the current popup. However, this would be more than a simple change, I guess...

**Comment by farfromrefug** [comment]
@CheariX should be fixed in latest i just released. I looked into the OCR part.

**Comment by CheariX** [comment]
> @CheariX should be fixed in latest i just released. 

Unfortunately, I still get the same error as shown above. 

I just tried to reset/reinstall the app but still, I get the same error.
I'm on version 1.11.2.

> I looked into the OCR part.

Thank you. Appreciated.

**Comment by farfromrefug** [comment]
@CheariX crazy i can't reproduce that...
Will look deeper

**Comment by Comprehensive-Jason** [comment]
I just came across this issue too! #302

**Comment by Comprehensive-Jason** [comment]
@farfromrefug I tried the new version via F-Droid, but the problem still exists.

**Comment by farfromrefug** [comment]
@Comprehensive-Jason crazy i dont know where it comes from. I tied a fix as I can't reproduce it. Seems that wasnt it...
Will try again

**Comment by Comprehensive-Jason** [comment]
Is it related to the settings you pick in the app? If so, could you add a feature to reset all settings to default, to see if that fixes the 'undefined' issue with the JSON?

**Comment by Comprehensive-Jason** [comment]
It seems to be fixed now! @CheariX, can you check and verify?

**Comment by CheariX** [comment]
Yes. The latest version fixed the issue.

Thank you again for taking care of it an integrating the feature so quickly.

**Comment by Comprehensive-Jason** [comment]
Awesome. I will close #302 then.
