### ISSUE TITLE
Syncing Issues

### ISSUE THREAD

**Issue by DickinsonSa** [Akylas/OSS-DocumentScanner#9]
Hi,

Fantastic little app - many thanks and well done.

Would you mind clearing something up please...?

I set up the webdav sync, clicked on test and got the 'successful' reply. However, the sync circle is dimmed out and it just doesn't seem to sync any documents.

Have I missed doing something?

Version 1.0.2 build 3
Android 10

Thanks.

**Comment by farfromrefug** [comment]
@DickinsonSa thanks for the kind words.  
so yes if the test passes your documents should sync on your WebDAV folder(in an app specific format).
so you know. a sync should happen on doc add/remove/update. in this case the doc should be updated on your WebDAV folder.
so it is only one way sync. you can force the 2/way sync by manually pressing the sync button on the main page.
i will test it all again here to see if it works.

**Comment by farfromrefug** [comment]
> Appreciate the speedy feedback. Thanks for rechecking.

I fixed it it will be released between today and tomorrow

**Comment by DickinsonSa** [comment]
You're a little star!

Thanks for fixing it so quickly.

I'll give it a test and update how I get on so can close this one then. 

Great work on the project - best scanner I've used in a long time. 

Cheers.

**Comment by DickinsonSa** [comment]
I got the latest update, but I'm still not seeing it sync anything. Could I have missed something?

Still getting a 'success' when doing the test.

It's there a log anywhere?

**Comment by DickinsonSa** [comment]
Sounds like a plan. Thanks for that.

**Comment by DickinsonSa** [comment]
Or - if it's easier, drop the scans into a folder in 'downloads' - whatever suits you sir.

**Comment by farfromrefug** [comment]
@DickinsonSa If what you want are PDF in download folder you can already do that with the action bar PDF button. syncing is there so that you get back your document if you uninstall/install the app

**Comment by farfromrefug** [comment]
@DickinsonSa  could you please install [this](http://gofile.me/4pKGL/5dacOArni) build. That build has sentry enabled (personal hosted sentry instance). 
* Try to add a new document, 
* wait like 30s
* then go to settings and long press the version number
* kill and restart the app.
* I should get a bug report showing me the sync logs
Thanks!

**Comment by DickinsonSa** [comment]
Hi,

Initially got a 'failed to create folder' message on start up.

When long pressing on version number got...

Error / Test error - pressed 'ok'.

Thanks, hope it helps.

Cheers
----------------------------------------

16 Dec 2023 18:04:03 farfromrefuge ***@***.***>:

**Comment by farfromrefug** [comment]
@DickinsonSa i got an error report just now which i think is from you (Huawei P20 android 10 ? )
If so it tells me that you dont have the right create a folder in your webdav config.
It can mean multiple things. What is your webdav server? is it something like nextcloud? a nas? 
It could either be that you actually cant create folders
But it could also comes from the fact that right now the only authentication i support is `Basic authentication`. Maybe your server use a different tech ? like digest or token?

**Comment by DickinsonSa** [comment]
Hi,

I'm running webdav on Hetzner storage share - if that helps.

I saw the folder error, but it didn't make sense - I already created the folder for the scan output.

Wasn't sure if I'd configured the folder path correctly, but it did give me a 'success' message - so I assumed all OK.

Thanks for looking.

I can give you the storage share address if it helps.

Cheers
----------------------------------------

16 Dec 2023 18:14:23 farfromrefuge ***@***.***>:

**Comment by farfromrefug** [comment]
@DickinsonSa ok i think we will need to work closer on this. My need you to create a me a test account just so that i can test myself. THen you could remove it. Could you send me a mail at contact at akylas dot fr so that we can work it out?

**Comment by DickinsonSa** [comment]
Hi,

Yes, I'll do that, unfortunately I'm away from home at the moment but should get back on Monday.

Is that alright with you?

I really appreciate you taking the time to sort this and  will help any way I can.

Cheers

----------------------------------------

16 Dec 2023 18:21:55 farfromrefuge ***@***.***>:

**Comment by farfromrefug** [comment]
@DickinsonSa no problem whenever you can. enjoy your week end
